name: LeetcodeOS
options:
  bundleIdPrefix: com.djsly
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: QGMAWHX827
    MARKETING_VERSION: 1.0.1
    CURRENT_PROJECT_VERSION: 1
targets:
  LeetcodeOS:
    type: application
    platform: iOS
    sources:
      - LeetcodeOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.djsly.leetcodeos
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: 1
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SUPPORTS_XR_DESIGNED_FOR: NO
    info:
      path: LeetcodeOS/Resources/Info.plist
      properties:
        CFBundleName: LeetcodeOS
        CFBundleDisplayName: leetcodeOS
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen: {}
        UIUserInterfaceStyle: Dark
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSupportsIndirectInputEvents: true
        NSLocalNetworkUsageDescription: "leetcodeOS needs local network access to connect to your terminal server."
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
          NSExceptionDomains:
            tail40af16.ts.net:
              NSIncludesSubdomains: true
              NSExceptionAllowsInsecureHTTPLoads: true
        NSBonjourServices:
          - _http._tcp
